# SPDX-License-Identifier: GPL-2.0-or-later
#requires -Version 5.1
<#
.SYNOPSIS
  Overlay CoinLine sources into MAME, then build SUBTARGET=coinline via MSYS2.

.PARAMETER ShellFlavor
  MINGW64 (default for MAME: makefile requires MSYSTEM=MINGW64 / MINGW64 set), or UCRT64 | CLANG64 | MSYS2.

.NOTES
  MAME 0.287 makefile has no UCRT64 branch; UCRT64 leaves MINGW64 unset and breaks the Windows target. Use MINGW64 for builds unless you patch MAME.
#>
param(
    [string] $MsysRoot = 'C:\msys64',
    [string] $MameRoot = '',
    [int] $Jobs = 0,
    [ValidateSet('UCRT64', 'CLANG64', 'MINGW64', 'MSYS2')]
    [string] $ShellFlavor = 'MINGW64'
)

$ErrorActionPreference = 'Stop'
if ($Jobs -le 0) {
    $Jobs = [int]$env:NUMBER_OF_PROCESSORS
    if ($Jobs -le 0) { $Jobs = 8 }
}

$EmuRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
if (-not $MameRoot) {
    if ($env:EXTERNAL_MAME_ROOT) {
        $MameRoot = $env:EXTERNAL_MAME_ROOT
    }
    else {
        $MameRoot = Join-Path $EmuRoot 'third-party\mame'
    }
}

& (Join-Path $PSScriptRoot 'overlay-coinline-driver.ps1') -EmuRoot $EmuRoot -MameRoot $MameRoot
if ($LASTEXITCODE -ne 0) { throw 'overlay-coinline-driver.ps1 failed' }

if (-not (Test-Path -LiteralPath $MameRoot)) {
    throw "MAME root not found: $MameRoot. Run bootstrap-msys2-mame.ps1 first."
}

$Bash = Join-Path $MsysRoot 'usr\bin\bash.exe'
if (-not (Test-Path -LiteralPath $Bash)) {
    throw "bash.exe not found: $Bash"
}

function Convert-ToUnixMsysPath([string]$WinPath) {
    if ($WinPath -match '^([A-Za-z]):\\(.*)$') {
        $d = $Matches[1].ToLowerInvariant()
        $r = $Matches[2] -replace '\\', '/'
        return "/$d/$r"
    }
    return ($WinPath -replace '\\', '/')
}

$LogDir = Join-Path $EmuRoot 'build\logs'
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
$LogFile = Join-Path $LogDir 'mame-build.log'
if (Test-Path -LiteralPath $LogFile) {
    Remove-Item -LiteralPath $LogFile -Force
}

$InnerWin = (Resolve-Path (Join-Path $PSScriptRoot '_build_mame_inner.sh')).Path
$wrapWin = Join-Path $EmuRoot 'build\_coinline_mame_build_entry.sh'
$EmuU = Convert-ToUnixMsysPath $EmuRoot
$MameU = Convert-ToUnixMsysPath $MameRoot
$InnerU = Convert-ToUnixMsysPath $InnerWin
$MsysU = Convert-ToUnixMsysPath $MsysRoot
$wrapBody = @"
#!/usr/bin/bash
# Generated by build-mame-coinline.ps1
set -euo pipefail
export COINLINE_EMU_ROOT='$EmuU'
export EXTERNAL_MAME_ROOT='$MameU'
export COINLINE_MAKE_JOBS='$Jobs'
export COINLINE_MSYS_ROOT='$MsysU'
exec /usr/bin/bash -euo pipefail '$InnerU'
"@
[System.IO.File]::WriteAllText($wrapWin, $wrapBody, [System.Text.UTF8Encoding]::new($false))

$tempWrap = Join-Path $env:TEMP 'coinline-mame-build-entry.sh'
Copy-Item -LiteralPath $wrapWin -Destination $tempWrap -Force
$msysName = switch ($ShellFlavor) {
    'UCRT64' { 'UCRT64' }
    'CLANG64' { 'CLANG64' }
    'MINGW64' { 'MINGW64' }
    'MSYS2' { 'MSYS' }
    default { 'MINGW64' }
}
$CygpathExe = Join-Path $MsysRoot 'usr\bin\cygpath.exe'
$wrapArg = (& $CygpathExe @('-u', $tempWrap)).Trim()
$sw = [System.Diagnostics.Stopwatch]::StartNew()
# Login shell + Unix path (avoid PowerShell `-c` / CMD eating `/` in paths).
$env:MSYSTEM = $msysName
try {
    & $Bash @('--login', $wrapArg)
}
finally {
    Remove-Item Env:MSYSTEM -ErrorAction SilentlyContinue
}
$exitCode = $LASTEXITCODE
$sw.Stop()
$proc = [pscustomobject]@{ ExitCode = $exitCode }

$candidates = @(
    (Join-Path $MameRoot 'mamecoinline.exe'),
    (Join-Path $MameRoot 'mame.exe'),
    (Join-Path $MameRoot 'mame64.exe')
)
$exe = $candidates | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
if ($proc.ExitCode -ne 0 -or -not $exe) {
    $br = [ordered]@{
        command       = "MSYSTEM=$msysName bash --login $wrapArg"
        exit_code     = $proc.ExitCode
        elapsed_ms    = [int]$sw.ElapsedMilliseconds
        executable_path = $exe
        executable_exists = [bool]$exe
        log_path      = $LogFile
        success       = $false
        timestamp_utc = (Get-Date).ToUniversalTime().ToString('o')
    }
    $br | ConvertTo-Json -Depth 4 | Set-Content (Join-Path $EmuRoot 'build\build-result.json') -Encoding UTF8
    throw "MAME make failed (exit $($proc.ExitCode)) or executable missing. See $LogFile"
}

$BinDir = Join-Path $EmuRoot 'build\bin'
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
$Dest = Join-Path $BinDir 'coinline-mame.exe'
Copy-Item -LiteralPath $exe -Destination $Dest -Force

$hash = (Get-FileHash -LiteralPath $Dest -Algorithm SHA256).Hash.ToLowerInvariant()
$brOk = [ordered]@{
    command            = "MSYSTEM=$msysName bash -l -c make REGENIE=1 SUBTARGET=coinline -j$Jobs (via $Bash)"
    exit_code          = $proc.ExitCode
    elapsed_ms         = [int]$sw.ElapsedMilliseconds
    executable_path    = $Dest
    source_executable  = $exe
    executable_exists  = $true
    executable_sha256  = $hash
    log_path           = $LogFile
    success            = $true
    timestamp_utc      = (Get-Date).ToUniversalTime().ToString('o')
}
$brOk | ConvertTo-Json -Depth 4 | Set-Content (Join-Path $EmuRoot 'build\build-result.json') -Encoding UTF8
Write-Host "Copied emulator to $Dest"
Write-Host 'build-mame-coinline.ps1 finished OK.'
exit 0
