# SPDX-License-Identifier: GPL-2.0-or-later
#requires -Version 5.1
<#
.SYNOPSIS
  Validate boot-trace.jsonl / boot-milestones.json from a real emulator run.
#>
param(
    [string] $BootTracePath = '',
    [string] $RunDir = '',
    [switch] $AllowIncomplete,
    [switch] $BootTraceSmoke
)

$ErrorActionPreference = 'Stop'

if (-not $BootTracePath) {
    if (-not $RunDir) { throw 'Provide -BootTracePath or -RunDir' }
    $BootTracePath = Join-Path $RunDir 'boot-trace.jsonl'
}
if (-not (Test-Path -LiteralPath $BootTracePath)) {
    throw "Boot trace missing: $BootTracePath"
}

$sequence = [System.Collections.Generic.List[string]]::new()
$objects = [System.Collections.Generic.List[object]]::new()
$lines = Get-Content -LiteralPath $BootTracePath -ErrorAction Stop
foreach ($line in $lines) {
    $t = $line.Trim()
    if (-not $t) { continue }
    try {
        $o = $t | ConvertFrom-Json
    }
    catch {
        throw "Invalid JSONL in boot trace: $line"
    }
    if (-not $o.milestone) {
        throw "Boot trace line missing milestone: $line"
    }
    $sequence.Add([string]$o.milestone)
    $objects.Add($o)
}

$need = @('M0', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M8', 'M9', 'M10')
if ($BootTraceSmoke) {
    $need = @('M0', 'M1', 'M2', 'M3', 'M4', 'M5')
}
elseif ($AllowIncomplete) {
    $need = @('M0', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M8', 'M9')
}
$firstPos = @{}
for ($i = 0; $i -lt $sequence.Count; $i++) {
    $m = $sequence[$i]
    if (-not $firstPos.ContainsKey($m)) {
        $firstPos[$m] = $i
    }
}

$missing = @()
foreach ($m in $need) {
    if (-not $firstPos.ContainsKey($m)) {
        $missing += $m
    }
}
# M7 slot: legacy keypad milestone `M7` or telephony subdivisions `M7A`/`M7B`/`M7C`.
$m7SlotOk = $false
foreach ($m in @('M7', 'M7A', 'M7B', 'M7C')) {
    if ($firstPos.ContainsKey($m)) {
        $m7SlotOk = $true
        break
    }
}
if (-not $m7SlotOk) {
    $missing += 'M7'
}
# Require strict M0 < M1 < ... < M4. M5..M9 may appear in any order after M4; M10 must be after M4 and
# after all of M5..M9 that are present (firmware may hit VFD before keypad, etc.).
$orderBad = $false
$chain = @('M0', 'M1', 'M2', 'M3', 'M4')
$lastIndex = -1
foreach ($m in $chain) {
    if (-not $firstPos.ContainsKey($m)) {
        $orderBad = $true
        break
    }
    $p = $firstPos[$m]
    if ($lastIndex -ge 0 -and $p -le $lastIndex) {
        $orderBad = $true
        break
    }
    $lastIndex = $p
}
if (-not $orderBad -and $firstPos.ContainsKey('M4')) {
    $p4 = $firstPos['M4']
    $max59 = -1
    foreach ($m in @('M5', 'M6', 'M7', 'M7A', 'M7B', 'M7C', 'M8', 'M9')) {
        if ($firstPos.ContainsKey($m) -and $firstPos[$m] -lt $p4) { $orderBad = $true; break }
        if ($firstPos.ContainsKey($m) -and $firstPos[$m] -gt $max59) { $max59 = $firstPos[$m] }
    }
    if (-not $orderBad -and $firstPos.ContainsKey('M10')) {
        if ($firstPos['M10'] -lt $p4) { $orderBad = $true }
        elseif ($max59 -ge 0 -and $firstPos['M10'] -lt $max59) { $orderBad = $true }
    }
}

$blockerDir = if ($RunDir) { $RunDir } else { Split-Path -Parent $BootTracePath }
$ioPath = Join-Path $blockerDir 'io-trace.jsonl'
$ioTail = ''
if (Test-Path -LiteralPath $ioPath) {
    $ioTail = (Get-Content -LiteralPath $ioPath -Tail 100) -join "`n"
}

$highest = 'none'
foreach ($m in @('M10', 'M9', 'M8', 'M7C', 'M7B', 'M7A', 'M7', 'M6', 'M5V', 'M5', 'M4', 'M3', 'M2', 'M1', 'M0')) {
    if ($firstPos.ContainsKey($m)) {
        $highest = $m
        break
    }
}

if ($missing.Count -gt 0 -or $orderBad) {
    $blockerPath = Join-Path $blockerDir 'boot-blocker.md'
    $obs = $sequence -join ', '
    $missTxt = if ($missing.Count) { $missing -join ', ' } else { '(none)' }
    $lastObj = if ($objects.Count) { $objects[$objects.Count - 1] | ConvertTo-Json -Compress -Depth 8 } else { '{}' }
    @"
# Boot blocker

- **Boot trace**: ``$BootTracePath``
- **Highest milestone observed**: $highest
- **Observed milestone sequence**: $obs
- **Missing milestones**: $missTxt
- **Out-of-order first occurrences**: $(if ($orderBad) { 'yes' } else { 'no' })
- **Last boot-trace object**: $lastObj

## Last 100 I/O trace lines

``````
$ioTail
``````

## Firmware source hints

Set ``FIRMWARE_SOURCE_ROOT`` / ``COINLINE_EMU_ROOT`` and search the resolved tree for port numbers from ``unknown-ports.json``.

## Next emulator files

- ``src/mame/coinline/millennium_io.cpp`` — port decode / defaults
- ``src/mame/coinline/millennium_state.cpp`` — milestone timers / device init

Generated by ``tools/windows/validate-boot-milestones.ps1``.
"@ | Set-Content -LiteralPath $blockerPath -Encoding UTF8
    Write-Error "Boot milestone validation failed. See $blockerPath"
    if ($AllowIncomplete) { exit 2 }
    exit 1
}

if (-not $AllowIncomplete -and -not $BootTraceSmoke) {
    $lastM10 = ($lines | Where-Object { $_ -match '"milestone"\s*:\s*"M10"' } | Select-Object -Last 1)
    if ($lastM10) {
        $j = $lastM10.Trim() | ConvertFrom-Json
        if ($null -ne $j.idle -and -not [bool]$j.idle) {
            $blockerPath = Join-Path $blockerDir 'boot-blocker.md'
            @"
# Boot blocker (M10 idle=false)

- **Highest milestone**: M10 present but idle gate false.
- **Line**: $($lastM10.Trim())

See io-trace and unknown-ports in this directory.
"@ | Set-Content -LiteralPath $blockerPath -Encoding UTF8
            throw 'M10 present but idle=false.'
        }
    }
}

Write-Host "Boot milestones validated (highest first-hit in trace: $highest)."
exit 0
