// SPDX-License-Identifier: GPL-2.0-or-later

#include "emu.h"
#include "millennium.h"

INPUT_PORTS_START(millennium)
	PORT_START("KEYMATRIX")
	PORT_BIT(0x00000001, IP_ACTIVE_HIGH, IPT_KEYPAD) PORT_NAME("1") PORT_CODE(KEYCODE_1) PORT_CODE(KEYCODE_1_PAD)
	PORT_BIT(0x00000002, IP_ACTIVE_HIGH, IPT_KEYPAD) PORT_NAME("2") PORT_CODE(KEYCODE_2) PORT_CODE(KEYCODE_2_PAD)
	PORT_BIT(0x00000004, IP_ACTIVE_HIGH, IPT_KEYPAD) PORT_NAME("3") PORT_CODE(KEYCODE_3) PORT_CODE(KEYCODE_3_PAD)
	PORT_BIT(0x00000008, IP_ACTIVE_HIGH, IPT_KEYPAD) PORT_NAME("4") PORT_CODE(KEYCODE_4) PORT_CODE(KEYCODE_4_PAD)
	PORT_BIT(0x00000010, IP_ACTIVE_HIGH, IPT_KEYPAD) PORT_NAME("5") PORT_CODE(KEYCODE_5) PORT_CODE(KEYCODE_5_PAD)
	PORT_BIT(0x00000020, IP_ACTIVE_HIGH, IPT_KEYPAD) PORT_NAME("6") PORT_CODE(KEYCODE_6) PORT_CODE(KEYCODE_6_PAD)
	PORT_BIT(0x00000040, IP_ACTIVE_HIGH, IPT_KEYPAD) PORT_NAME("7") PORT_CODE(KEYCODE_7) PORT_CODE(KEYCODE_7_PAD)
	PORT_BIT(0x00000080, IP_ACTIVE_HIGH, IPT_KEYPAD) PORT_NAME("8") PORT_CODE(KEYCODE_8) PORT_CODE(KEYCODE_8_PAD)
	PORT_BIT(0x00000100, IP_ACTIVE_HIGH, IPT_KEYPAD) PORT_NAME("9") PORT_CODE(KEYCODE_9) PORT_CODE(KEYCODE_9_PAD)
	PORT_BIT(0x00000200, IP_ACTIVE_HIGH, IPT_KEYPAD) PORT_NAME("Keypad *") PORT_CODE(KEYCODE_ASTERISK)
	PORT_BIT(0x00000400, IP_ACTIVE_HIGH, IPT_KEYPAD) PORT_NAME("0") PORT_CODE(KEYCODE_0) PORT_CODE(KEYCODE_0_PAD)
	PORT_BIT(0x00000800, IP_ACTIVE_HIGH, IPT_KEYPAD) PORT_NAME("Keypad #") PORT_CODE(KEYCODE_SLASH_PAD)
	PORT_BIT(0x00001000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("New Call") PORT_CODE(KEYCODE_N)
	PORT_BIT(0x00002000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Dial pad B (DTMF)") PORT_CODE(KEYCODE_F2)
	PORT_BIT(0x00004000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Dial pad C (DTMF)") PORT_CODE(KEYCODE_F3)
	PORT_BIT(0x00008000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Dial pad D (DTMF)") PORT_CODE(KEYCODE_F4)
	PORT_BIT(0x00010000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("VOL+") PORT_CODE(KEYCODE_EQUALS)
	PORT_BIT(0x00020000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("VOL-") PORT_CODE(KEYCODE_MINUS)
	PORT_BIT(0x00040000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Language") PORT_CODE(KEYCODE_L)
	PORT_BIT(0x00080000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Handset Lift") PORT_TOGGLE PORT_CODE(KEYCODE_H)
	// Rep-dial / speed-dial buttons 1–10 → TP→CP 0x40…0x52 (even bytes); bits 20–29.
	PORT_BIT(0x00100000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Rep dial 1") PORT_CODE(KEYCODE_Q)
	PORT_BIT(0x00200000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Rep dial 2") PORT_CODE(KEYCODE_W)
	PORT_BIT(0x00400000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Rep dial 3") PORT_CODE(KEYCODE_E)
	PORT_BIT(0x00800000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Rep dial 4") PORT_CODE(KEYCODE_R)
	PORT_BIT(0x01000000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Rep dial 5") PORT_CODE(KEYCODE_T)
	PORT_BIT(0x02000000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Rep dial 6") PORT_CODE(KEYCODE_Y)
	PORT_BIT(0x04000000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Rep dial 7") PORT_CODE(KEYCODE_G)
	PORT_BIT(0x08000000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Rep dial 8") PORT_CODE(KEYCODE_J)
	PORT_BIT(0x10000000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Rep dial 9") PORT_CODE(KEYCODE_X)
	PORT_BIT(0x20000000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Rep dial 10") PORT_CODE(KEYCODE_Z)
	// DTMF A (TP→CP 0x20); row0/col3 on TP-fed KEYMATRIX — not visible on CP 8255 reads.
	PORT_BIT(0x40000000, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Dial pad A (DTMF)") PORT_CODE(KEYCODE_TILDE)

	// 11-line VFD soft keys / direction keys (TP→CP 0x90…0x9B). Separate port so KEYMATRIX stays within 32 bits.
	PORT_START("TERMINAL21_SOFTKEYS")
	PORT_BIT(0x001, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SK top left") PORT_CODE(KEYCODE_HOME)
	PORT_BIT(0x002, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SK mid left") PORT_CODE(KEYCODE_END)
	PORT_BIT(0x004, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SK bot left") PORT_CODE(KEYCODE_PGUP)
	PORT_BIT(0x008, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SK top right") PORT_CODE(KEYCODE_PGDN)
	PORT_BIT(0x010, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SK mid right") PORT_CODE(KEYCODE_INSERT)
	PORT_BIT(0x020, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SK bot right") PORT_CODE(KEYCODE_DEL)
	PORT_BIT(0x040, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SK up") PORT_CODE(KEYCODE_UP)
	PORT_BIT(0x080, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SK down") PORT_CODE(KEYCODE_DOWN)
	PORT_BIT(0x100, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SK left") PORT_CODE(KEYCODE_LEFT)
	PORT_BIT(0x200, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SK right") PORT_CODE(KEYCODE_RIGHT)
	PORT_BIT(0x400, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SK spare 1") PORT_CODE(KEYCODE_TAB)
	PORT_BIT(0x800, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("SK spare 2") PORT_CODE(KEYCODE_BACKSLASH)

	PORT_START("SECMASK")
	// Active-low closed-state defaults: lock/door/vault low at boot unless toggled by user.
	PORT_BIT(0x01, 0x00, IPT_OTHER) PORT_NAME("Lock") PORT_TOGGLE PORT_CODE(KEYCODE_F5)
	PORT_BIT(0x02, 0x00, IPT_OTHER) PORT_NAME("Door") PORT_TOGGLE PORT_CODE(KEYCODE_F6)
	PORT_BIT(0x04, 0x00, IPT_OTHER) PORT_NAME("Vault") PORT_TOGGLE PORT_CODE(KEYCODE_F7)
	PORT_BIT(0x08, 0x00, IPT_OTHER) PORT_NAME("Service") PORT_CODE(KEYCODE_F8)

	PORT_START("CARDUI")
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Magstripe swipe") PORT_CODE(KEYCODE_F9)
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Smartcard insert") PORT_CODE(KEYCODE_F10)

	PORT_START("COINUI")
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Coin insert") PORT_CODE(KEYCODE_F11)
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Coin return") PORT_CODE(KEYCODE_F12)
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Coin jam (test)") PORT_CODE(KEYCODE_PAUSE)

	PORT_START("LINECTRL")
	// terminal_21_user_io: LINE_CONNECTION (0x66) vs LINE_INTERRUPTION (0x64); LINE_REVERSAL_0 (0x68) / LINE_REVERSAL_1 (0x6A).
	// terminal_21 line_supervision_gating: when bit 3 set, reversal pulses are suppressed (relay/switching model).
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Line connected (LINE_CONNECTION)") PORT_CODE(KEYCODE_U)
	PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Line reversal 0 (LINE_REVERSAL_0)") PORT_CODE(KEYCODE_I)
	PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Line reversal 1 (LINE_REVERSAL_1)") PORT_CODE(KEYCODE_O)
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_OTHER) PORT_NAME("Suppress line reversals (relay/switching gate)") PORT_CODE(KEYCODE_COMMA)
INPUT_PORTS_END

ROM_START(cl_millennium)
	ROM_REGION(0x100000, "flash", ROMREGION_ERASEFF)
	// Voiceware: 1 MiB each, 8 x 128 KiB banks per chip in one 2 MiB region (16 banks for uPD7759 `set_rom_bank`).
	ROM_REGION(0x200000, "voicew", 0)
	ROM_LOAD("voice_a.bin", 0x000000, 0x100000, CRC(3d3f5c1d) SHA1(7a43f3b52c7f437ab5cd9431a6ead6cb10f23003))
	ROM_LOAD("voice_b.bin", 0x100000, 0x100000, CRC(31364d9b) SHA1(697b5fc218633cbcd8602199375744c2d46231fd))
ROM_END

tiny_rom_entry const *millennium_state::device_rom_region() const { return ROM_NAME(cl_millennium); }

ioport_constructor millennium_state::device_input_ports() const { return INPUT_PORTS_NAME(millennium); }

COMP(2026, cl_millennium, 0, 0, millennium, millennium, millennium_state, empty_init, "CoinLine",
	"Millennium Z180 terminal", MACHINE_NOT_WORKING)
